/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 45P3R4 (https://sketchfab.com/45P3R4)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/keyboard-ba869e8681974cf088736173b8b86fef
title: keyboard
*/
import React, { Suspense } from "react";
import { Stats, OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import KeyboardModel from "./KeyboardModel";

export default function KeyboardAnimation() {
  return (
    <Canvas>
      <ambientLight intensity={1} />
      <pointLight color="white" intensity={1} position={[10, 10, 10]} />
      <Suspense>
        <KeyboardModel />
      </Suspense>
      <OrbitControls autoRotate enableZoom={false} />
    </Canvas>
  );
}
